// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkzphcriwsbknrweehhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrenBoY3Jpd3Nia25yd2VlaGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTE0NjYsImV4cCI6MjA3NDY2NzQ2Nn0.s1yOvIQCSQPG8akQx79116tqbmB3Kce_Cxda-09zCAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});